site_name: Cyberz
theme:
  name: material
  font:
    text: Roboto Mono
  favicon: images/cyberz_4_small.jpg
  icon:
    logo: cyberz-main
  palette:
    - scheme: 'slate'
      primary: 'black'
      accent: 'blue'
  features:
    - navigation.tabs
    - navigation.top
    - navigation.tabs.sticky
    - toc.integrate
    - navigation.instant
    - header.autohide
    - search.highlight
    - search.suggest
    - search.share
    - navigation.indexes
  custom_dir: overrides

plugins:
  - glightbox

nav:
  - About Cyberz: index.md
  - The Game:
      - â„¹ï¸ Overview: overview.md
      - ğŸ•¹ï¸ Gameplay: gameplay.md
      - ğŸ’¼ Job Missions: missions.md
      - ğŸ¤– Bots: bots.md
      - ğŸ†“ Free 2 Play: free2play.md
  - Lore:
      - ğŸ“– Game Lore: lore.md
      - ğŸ’° La'Brett: laBrett.md
      - ğŸ’» Syd the Skid: sydTheSkid.md
      - ğŸ¹ Hunter: hunter.md
  - $BYTE: byte.md
  - Roadmap: roadmap.md
  - The Team: team.md

markdown_extensions:
  - admonition
  - md_in_html
  - attr_list
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      options:
        custom_icons:
          - overrides/.icons

extra:
  social:
    - icon: cyberz-main
      link: https://www.cyberzgame.com
    - icon: fontawesome/brands/discord
      link: https://discord.gg/cyberzgame
    - icon: fontawesome/brands/twitter
      link: https://x.com/CyberzGame
